[package]
version = "0.1.0"
name = "contract_elf"
edition = "2021"

[dependencies]
sdk = { workspace = true, features = ["sp1"] }
sp1-zkvm = "4.1.0"
sp1-ticket-contract = { path = "../lib", package = "contract"}

